import { Mood, Style, AspectRatio, IntroType, TextAnimationStyle, TextAnimationSpeed, SoundEffect, ParticleType, Resolution, ImageFilter } from './types';

export const LOADING_MESSAGES = [
  "Warming up the virtual cameras...",
  "Adjusting the lighting and focus...",
  "Rendering cinematic atoms...",
  "Consulting with the director of photography...",
  "Our AI director is calling 'Action!'...",
  "Polishing the final cut, this might take a moment...",
  "Adding a touch of Hollywood magic...",
];

// FIX: Explicitly type the array literal before sorting to prevent TypeScript from widening the `value` property to `string`.
export const MOOD_OPTIONS: { label: string; value: Mood }[] = ([
    { label: '🗺️ Adventurous', value: 'Adventurous' },
    { label: '😰 Anxious', value: 'Anxious' },
    { label: '💥 Chaotic', value: 'Chaotic' },
    { label: '🎬 Cinematic', value: 'Cinematic' },
    { label: '😂 Comedic', value: 'Comedic' },
    { label: '🎭 Dramatic', value: 'Dramatic' },
    { label: '☁️ Dreamy', value: 'Dreamy' },
    { label: '✨ Energetic', value: 'Energetic' },
    { label: '🌌 Ethereal', value: 'Ethereal' },
    { label: '🎄 Festive', value: 'Festive' },
    { label: '🚀 Futuristic', value: 'Futuristic' },
    { label: '🏙️ Gritty', value: 'Gritty' },
    { label: '🙏 Hopeful', value: 'Hopeful' },
    { label: '👻 Horror', value: 'Horror' },
    { label: '😄 Joyful', value: 'Joyful' },
    { label: '👑 Majestic', value: 'Majestic' },
    { label: '😔 Melancholic', value: 'Melancholic' },
    { label: '😈 Mischievous', value: 'Mischievous' },
    { label: '🕵️ Mysterious', value: 'Mysterious' },
    { label: '🕰️ Nostalgic', value: 'Nostalgic' },
    { label: '🔮 Ominous', value: 'Ominous' },
    { label: '😌 Peaceful', value: 'Peaceful' },
    { label: '😜 Playful', value: 'Playful' },
    { label: '🤔 Reflective', value: 'Reflective' },
    { label: '❤️ Romantic', value: 'Romantic' },
    { label: '🧘‍♀️ Serene', value: 'Serene' },
    { label: '😔 Somber', value: 'Somber' },
    { label: '🕌 Spiritual', value: 'Spiritual' },
    { label: '😨 Suspenseful', value: 'Suspenseful' },
    { label: '🏞️ Tranquil', value: 'Tranquil' },
    { label: '🏆 Triumphant', value: 'Triumphant' },
    { label: '🙌 Uplifting', value: 'Uplifting' },
    { label: '🎞️ Vintage', value: 'Vintage' },
    { label: '🦄 Whimsical', value: 'Whimsical' },
] as { label: string; value: Mood }[]).sort((a,b) => a.label.localeCompare(b.label));

export const STYLE_OPTIONS: { label: string; value: Style }[] = ([
    { label: '🌀 Abstract', value: 'Abstract' },
    { label: '🌍 Afrofuturism', value: 'Afrofuturism' },
    { label: '🎌 Anime', value: 'Anime' },
    { label: '🎨 Art Brut', value: 'Art Brut' },
    { label: '🏛️ Art Deco', value: 'Art Deco' },
    { label: '🌿 Art Nouveau', value: 'Art Nouveau' },
    { label: '🏛️ Baroque', value: 'Baroque' },
    { label: '🏗️ Bauhaus', value: 'Bauhaus' },
    { label: '🧬 Biopunk', value: 'Biopunk' },
    { label: '⚪️ Black & White', value: 'Black and White' },
    { label: '📼 Cassette Futurism', value: 'Cassette Futurism' },
    { label: '🎅 Christmas', value: 'Christmas' },
    { label: '🧱 Claymation', value: 'Claymation' },
    { label: '📖 Comic Book', value: 'Comic Book' },
    { label: '🧊 Cubism', value: 'Cubism' },
    { label: '🤖 Cyberpunk', value: 'Cyberpunk' },
    { label: '🤪 Dadaism', value: 'Dadaism' },
    { label: '🏰 Dark Fantasy', value: 'Dark Fantasy' },
    { label: '🟥 De Stijl', value: 'De Stijl' },
    { label: '⚙️ Dieselpunk', value: 'Dieselpunk' },
    { label: '🎭 Expressionism', value: 'Expressionism' },
    { label: '🔮 Fantasy', value: 'Fantasy' },
    { label: '🎨 Fauvism', value: 'Fauvism' },
    { label: '🌸 Folk Art', value: 'Folk Art' },
    { label: '⏩ Futurism', value: 'Futurism' },
    { label: '🍃 Ghibli-esque', value: 'Ghibli-esque' },
    { label: '📺 Glitch Art', value: 'Glitch Art' },
    { label: '🦇 Gothic', value: 'Gothic' },
    { label: '🎨 Graffiti', value: 'Graffiti' },
    { label: '📸 Hyper-realistic', value: 'Hyper-realistic' },
    { label: '🎨 Impressionistic', value: 'Impressionistic' },
    { label: '🌙 Islamic Art', value: 'Islamic Art' },
    { label: '🎵 Lo-fi', value: 'Lo-fi' },
    { label: '🧊 Low Poly', value: 'Low Poly' },
    { label: '◽ Minimalist', value: 'Minimalist' },
    { label: '🏛️ Neoclassicism', value: 'Neoclassicism' },
    { label: '🕵️ Noir', value: 'Noir' },
    { label: '🎨 Oil Painting', value: 'Oil Painting' },
    { label: '👾 Pixel Art', value: 'Pixel Art' },
    { label: '🎨 Pointillism', value: 'Pointillism' },
    { label: '💥 Pop Art', value: 'Pop Art' },
    { label: '😵 Psychedelic', value: 'Psychedelic' },
    { label: '🏞️ Realism', value: 'Realism' },
    { label: '🎨 Renaissance', value: 'Renaissance' },
    { label: '👑 Rococo', value: 'Rococo' },
    { label: '❤️ Romanticism', value: 'Romanticism' },
    { label: '😱 Scream', value: 'Scream' },
    { label: '🚀 Sci-Fi', value: 'Sci-Fi' },
    { label: '✏️ Sketch', value: 'Sketch' },
    { label: '🌱 Solarpunk', value: 'Solarpunk' },
    { label: '⚙️ Steampunk', value: 'Steampunk' },
    { label: '🔳 Suprematism', value: 'Suprematism' },
    { label: '🤪 Surreal', value: 'Surreal' },
    { label: '🌃 Synthwave', value: 'Synthwave' },
    { label: '👻 Tim Burton', value: 'Tim Burton' },
    { label: '👁️ Trompe-l\'œil', value: 'Trompe-l\'œil' },
    { label: '👺 Ukiyo-e', value: 'Ukiyo-e' },
    { label: '🌴 Vaporwave', value: 'Vaporwave' },
    { label: '📼 Vintage Film', value: 'Vintage Film' },
    { label: '🧱 Voxel Art', value: 'Voxel Art' },
    { label: '💧 Watercolor', value: 'Watercolor' },
] as { label: string; value: Style }[]).sort((a, b) => a.label.localeCompare(b.label));

export const ASPECT_RATIO_OPTIONS: { label: string; value: AspectRatio }[] = [
    { label: 'Landscape (16:9)', value: '16:9' },
    { label: 'Portrait (9:16)', value: '9:16' },
    { label: 'Square (1:1)', value: '1:1' },
    { label: 'Standard TV (4:3)', value: '4:3' },
    { label: 'Cinema (2.39:1)', value: '2.39:1' },
];

export const RESOLUTION_OPTIONS: { label: string; value: Resolution }[] = [
    { label: 'SD (480p)', value: 'SD' },
    { label: 'HD (1080p)', value: 'HD' },
    { label: '4K (2160p)', value: '4K' },
];

const introTypes = ([
    { label: '📖 Book Open', value: 'Book Open' },
    { label: '🕒 Clock Wipe', value: 'Clock Wipe' },
    { label: '🔀 Crossfade', value: 'Crossfade' },
    { label: '🎭 Curtain Open', value: 'Curtain Open' },
    { label: '📟 Digital Scanlines', value: 'Digital Scanlines' },
    { label: '🎬 Dynamic Transition', value: 'Dynamic Transition' },
    { label: '⚫ Fade In/Out', value: 'Fade In/Out' },
    { label: '🎞️ Focus Pull', value: 'Focus Pull' },
    { label: '📺 Glitch Intro', value: 'Glitch Intro' },
    { label: '✏️ Hand-drawn Reveal', value: 'Hand-drawn Reveal' },
    { label: '💧 Ink Reveal', value: 'Ink Reveal' },
    { label: '👁️ Iris', value: 'Iris' },
    { label: '💠 Kaleidoscope', value: 'Kaleidoscope' },
    { label: '✨ Lens Flare', value: 'LensFlare' },
    { label: '💧 Liquid Metal', value: 'Liquid Metal' },
    { label: '▶️ Logo Animation', value: 'Logo Animation' },
    { label: '📽️ Old Film Projector', value: 'Old Film Projector' },
    { label: '💥 Particle Burst', value: 'Particle Burst' },
    { label: '👾 Pixelate In', value: 'Pixelate In' },
    { label: '💥 Shatter', value: 'Shatter' },
    { label: '➡️ Slide', value: 'Slide' },
    { label: '🎬 Stop Motion Reveal', value: 'Stop Motion Reveal' },
    { label: '⏳ Time-lapse Reveal', value: 'Time-lapse Reveal' },
    { label: '🔤 Title Card', value: 'Title Card' },
    { label: '↔️ Wipe', value: 'Wipe' },
    { label: '🔎 Zoom', value: 'Zoom' },
] as { label: string; value: IntroType }[]).sort((a, b) => a.label.localeCompare(b.label));


export const INTRO_TYPE_OPTIONS: { label: string; value: IntroType }[] = [
    { label: 'None', value: 'None' },
    ...introTypes,
];

// FIX: Explicitly type the array literal before sorting to prevent TypeScript from widening the `value` property to `string`.
export const TEXT_ANIMATION_STYLE_OPTIONS = ([
    { label: 'Blink', value: 'Blink' },
    { label: 'Bounce', value: 'Bounce' },
    { label: 'Chase', value: 'Chase' },
    { label: 'Drop In', value: 'Drop In' },
    { label: 'Echo', value: 'Echo' },
    { label: 'Elastic', value: 'Elastic' },
    { label: 'Fade In', value: 'Fade In' },
    { label: 'Flicker', value: 'Flicker' },
    { label: 'Flip', value: 'Flip' },
    { label: 'Fountain', value: 'Fountain' },
    { label: 'Glitch', value: 'Glitch' },
    { label: 'Glow', value: 'Glow' },
    { label: 'Jelly', value: 'Jelly' },
    { label: 'Pop', value: 'Pop' },
    { label: 'Pulse', value: 'Pulse' },
    { label: 'Shake', value: 'Shake' },
    { label: 'Slide In', value: 'Slide In' },
    { label: 'Spin', value: 'Spin' },
    { label: 'Strobe', value: 'Strobe' },
    { label: 'Stutter', value: 'Stutter' },
    { label: 'Swirl', value: 'Swirl' },
    { label: 'Typewriter', value: 'Typewriter' },
    { label: 'Wave', value: 'Wave' },
    { label: 'Wiggle', value: 'Wiggle' },
    { label: 'Wobble', value: 'Wobble' },
    { label: 'Zoom In', value: 'Zoom In' },
] as { label: string; value: TextAnimationStyle }[]).sort((a, b) => a.label.localeCompare(b.label));

export const TEXT_ANIMATION_SPEED_OPTIONS: { label: string; value: TextAnimationSpeed }[] = [
    { label: 'Slow', value: 'Slow' },
    { label: 'Normal', value: 'Normal' },
    { label: 'Fast', value: 'Fast' },
];

const soundEffects = ([
    { label: '👏 Applause', value: 'Applause', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
    { label: '🔔 Bell', value: 'Bell', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_100KB_MP3.mp3' },
    { label: '🐦 Birdsong', value: 'Birdsong', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
    { label: '📸 Camera', value: 'Camera', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_100KB_MP3.mp3' },
    { label: '💥 Explosion', value: 'Explosion', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
    { label: '🎅 Ho Ho Ho', value: 'HoHoHo', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_100KB_MP3.mp3' },
    { label: '✨ Magic Wand', value: 'MagicWand', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_100KB_MP3.mp3' },
    { label: '🌊 Ocean Waves', value: 'OceanWaves', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
    { label: '💧 Rain', value: 'Rain', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
    { label: '🌩️ Thunder', value: 'Thunder', url: 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_MP3.mp3' },
] as { label: string; value: SoundEffect; url: string }[]).sort((a,b) => a.label.localeCompare(b.label));

export const SOUND_EFFECT_OPTIONS: { label: string; value: SoundEffect; url: string }[] = [
    { label: 'None', value: 'None', url: '' },
    ...soundEffects,
];

export const PARTICLE_TYPE_OPTIONS: { label: string; value: ParticleType }[] = [
    { label: 'None', value: 'None' },
    { label: '✨ Sparkles', value: 'Sparkles' },
    { label: '💨 Dust', value: 'Dust' },
    { label: '🎉 Confetti', value: 'Confetti' },
    { label: '💧 Rain', value: 'Rain' },
    { label: '❄️ Snow', value: 'Snow' },
    { label: '🏮 Fireflies', value: 'Fireflies' },
];

export const IMAGE_FILTER_OPTIONS: { label: string; value: ImageFilter }[] = [
    { label: 'None', value: 'None' },
    { label: '🎞️ Sepia', value: 'Sepia' },
    { label: '⚫ Grayscale', value: 'Grayscale' },
    { label: '🔄 Invert', value: 'Invert' },
    { label: '🕰️ Vintage', value: 'Vintage' },
    { label: '🌈 Technicolor', value: 'Technicolor' },
    { label: '📷 Lomo', value: 'Lomo' },
    { label: '🖼️ Polaroid', value: 'Polaroid' },
];